# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: hyperloglog-analytics
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped